/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                    '#f8f9fa',
        'surface-bright':             '#f8f9fa',
        'surface-dim':                '#d9dadb',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f3f4f5',
        'surface-container':          '#edeeef',
        'surface-container-high':     '#e7e8e9',
        'surface-container-highest':  '#e1e3e4',
        'surface-variant':            '#e1e3e4',
        'on-surface':                 '#191c1d',
        'on-surface-variant':         '#444653',
        'on-background':              '#191c1d',
        'background':                 '#f8f9fa',
        'inverse-surface':            '#2e3132',
        'inverse-on-surface':         '#f0f1f2',
        'primary':                    '#3953bd',
        'on-primary':                 '#ffffff',
        'primary-container':          '#546cd7',
        'on-primary-container':       '#fffbff',
        'primary-fixed':              '#dde1ff',
        'primary-fixed-dim':          '#b9c3ff',
        'on-primary-fixed':           '#001356',
        'on-primary-fixed-variant':   '#1f3ba6',
        'inverse-primary':            '#b9c3ff',
        'secondary':                  '#754aa1',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#ce9ffd',
        'on-secondary-container':     '#5a3086',
        'secondary-fixed':            '#f0dbff',
        'secondary-fixed-dim':        '#dcb8ff',
        'on-secondary-fixed':         '#2c0051',
        'on-secondary-fixed-variant': '#5c3187',
        'tertiary':                   '#835100',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#a56600',
        'on-tertiary-container':      '#fffbff',
        'tertiary-fixed':             '#ffddb9',
        'tertiary-fixed-dim':         '#ffb964',
        'on-tertiary-fixed':          '#2b1700',
        'on-tertiary-fixed-variant':  '#663e00',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'outline':                    '#757684',
        'outline-variant':            '#c5c5d5',
        'surface-tint':               '#3c55bf',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body':     ['Inter', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
